apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: shop-operator
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: shop-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shop-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}