apiVersion: v1
kind: Service
metadata:
  name: shop-postgres-service
  labels:
    {{- include "shop.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
    {{- include "shop.selectorLabels" . | nindent 4 }}